//------------------------------------------------------------------------------
/*
    This file is part of rippled: https://github.com/ripple/rippled
    Copyright (c) 2012, 2013 Ripple Labs Inc.

    Permission to use, copy, modify, and/or distribute this software for any
    purpose  with  or without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies.

    THE  SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
    WITH  REGARD  TO  THIS  SOFTWARE  INCLUDING  ALL  IMPLIED  WARRANTIES  OF
    MERCHANTABILITY  AND  FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
    ANY  SPECIAL ,  DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER  RESULTING  FROM  LOSS  OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION  OF  CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/
//==============================================================================
#include <xrpl/basics/hardened_hash.h>
#include <xrpl/protocol/AccountID.h>
#include <xrpl/protocol/PublicKey.h>
#include <xrpl/protocol/digest.h>
#include <xrpl/protocol/tokens.h>

#include <algorithm>
#include <array>
#include <atomic>

namespace ripple {

namespace detail {

/** If true, we implement a cache for account ID lookups.

    This is generally a good idea and can improve performance, especially
    when serving client requests.

    The cache may generate warnings under some sanitizers; if you want to
    disable caching, set this variable to false.
 */
static constexpr bool cacheAccountIDs = true;

/** Represents a cached entry for the given AccountID.

    We keep the size and alignment of the structure at 64 bytes to
    make sure it fits within a cache line and avoid false sharing.
 */
struct alignas(64) CachedAccountID
{
    /** The sequence lock for the entry.

        An even value means that the data is stable, whereas an odd
        value indicates the data is being actively modified.

        We use a 32-bit value to ensure that the counter will never
        return to an observed value during a read window.
     */
    std::atomic<std::uint32_t> seq{0};

    /** The account id. */
    AccountID id{};

    /** The length of the cached encoding.

        This field disambiguates collisions between ACCOUNT_ZERO and
        never-written-to slots, since they would otherwise share the
        same encoded bits.
     */
    std::uint8_t len = 0;

    /** The actual string encoding. */
    char encoding[39] = {0};
};

// The actual cache to use: a simple, direct-mapped, best-effort construct.
//
// We do not use a hardened hash for this because an AccountID is already
// just cryptographically generated (i.e. uniformly distributed) bits and
// there is no amplification, since collisions do not carry an additional
// cost.
//
// The size is a "nice" power of 2 because it makes the calculation of an
// index easier.
constinit std::array<CachedAccountID, 65536> cache_{};

}  // namespace detail

std::string
toBase58(AccountID const& v)
{
    // Since the input bits are generated by a cryptographically secure
    // hash construct, we can just pick any subset of them, no muss, no
    // fuss.
    auto const index = [&v]() -> std::uint16_t {
        auto const data = v.data();

        return static_cast<std::uint16_t>(data[0]) |
            (static_cast<std::uint16_t>(data[1]) << 8);
    }();

    if constexpr (detail::cacheAccountIDs)
    {
        auto& slot = detail::cache_[index];

        // This is the optimistic, store-free read path: a collision with a
        // concurrent writer will be detected because the seq recheck fails
        // and we fall through to the slow path.
        //
        // These unsynchronized reads of the slot fields are, formally, data
        // races and, technically speaking, result in undefined behavior and
        // a tool like TSAN might flag them. These should not have an impact
        // on the correctness of the returned data: the sequence lock checks
        // ensure we discard any data that was in flux.
        if (auto const s0 = slot.seq.load(std::memory_order_acquire);
            (s0 & 1) == 0 && slot.len != 0 && slot.id == v)
        {
            // Bound the length before reading the buffer. This is an extra
            // safety check because the write path assert disappears, so we
            // can enforce the invariant even if the wrong size is stored.
            std::string ret(slot.encoding, std::min<std::size_t>(slot.len, 38));

            // This prevents the data loads above from sinking below the recheck
            // of seq. An acquire load alone does not, since it constrains later
            // operations, not earlier ones.
            std::atomic_thread_fence(std::memory_order_acquire);

            if (slot.seq.load(std::memory_order_relaxed) == s0)
                return ret;
        }
    }

    auto ret = encodeBase58Token(TokenType::AccountID, v.data(), v.size());

    XRPL_ASSERT(
        !ret.empty() && ret.size() <= 38,
        "ripple::toBase58 : maximum result size");

    if constexpr (detail::cacheAccountIDs)
    {
        auto& slot = detail::cache_[index];

        // Best-effort publish. The CAS to an odd value excludes other writers;
        // if it fails, another thread is publishing this slot and we won't
        // cache our result. Since this function is pure this (potentially)
        // costs one future encode and nothing more.
        if (auto s0 = slot.seq.load(std::memory_order_relaxed); (s0 & 1) == 0 &&
            slot.seq.compare_exchange_strong(
                s0, s0 + 1, std::memory_order_acquire))
        {
            // Release-ordered against the trailing store of s0 + 2 below. While
            // seq is odd, readers will bail at the parity gate; once it returns
            // to even, the ordering guarantees the data writes below are
            // visible to any reader that gets through.
            std::atomic_thread_fence(std::memory_order_release);

            slot.id = v;
            slot.len = static_cast<std::uint8_t>(ret.size());
            std::copy_n(ret.data(), ret.size(), slot.encoding);

            // Publishes the data stores before the new even value.
            slot.seq.store(s0 + 2, std::memory_order_release);
        }
    }

    return ret;
}

template <>
std::optional<AccountID>
parseBase58(std::string const& s)
{
    auto const result = decodeBase58Token(s, TokenType::AccountID);
    if (result.size() != AccountID::bytes)
        return std::nullopt;
    return AccountID{result};
}

//------------------------------------------------------------------------------
/*
    Calculation of the Account ID

    The AccountID is a 160-bit identifier that uniquely
    distinguishes an account. The account may or may not
    exist in the ledger. Even for accounts that are not in
    the ledger, cryptographic operations may be performed
    which affect the ledger. For example, designating an
    account not in the ledger as a regular key for an
    account that is in the ledger.

    Why did we use half of SHA512 for most things but then
    SHA256 followed by RIPEMD160 for account IDs? Why didn't
    we do SHA512 half then RIPEMD160? Or even SHA512 then RIPEMD160?
    For that matter why RIPEMD160 at all why not just SHA512 and keep
    only 160 bits?

    Answer (David Schwartz):

        The short answer is that we kept Bitcoin's behavior.
        The longer answer was that:
            1) Using a single hash could leave ripple
               vulnerable to length extension attacks.
            2) Only RIPEMD160 is generally considered safe at 160 bits.

        Any of those schemes would have been acceptable. However,
        the one chosen avoids any need to defend the scheme chosen.
        (Against any criticism other than unnecessary complexity.)

        "The historical reason was that in the very early days,
        we wanted to give people as few ways to argue that we were
        less secure than Bitcoin. So where there was no good reason
        to change something, it was not changed."
*/
AccountID
calcAccountID(PublicKey const& pk)
{
    static_assert(AccountID::bytes == sizeof(ripesha_hasher::result_type));

    ripesha_hasher rsh;
    rsh(pk.data(), pk.size());
    return AccountID{static_cast<ripesha_hasher::result_type>(rsh)};
}

AccountID const&
xrpAccount()
{
    static AccountID const account(beast::zero);
    return account;
}

AccountID const&
noAccount()
{
    static AccountID const account(1);
    return account;
}

bool
to_issuer(AccountID& issuer, std::string const& s)
{
    if (issuer.parseHex(s))
        return true;
    auto const account = parseBase58<AccountID>(s);
    if (!account)
        return false;
    issuer = *account;
    return true;
}

}  // namespace ripple
